//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется WindowsProject1.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_WINDOWSPROJECT1_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_WINDOWSPROJECT1			107
#define IDI_SMALL				108
#define IDC_WINDOWSPROJECT1			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1

#define IDC_LISTVIEW 101
#define ID_BUTTON_OPENDB 1001
#define IDD_DATABASE_DIALOG 1002
#define ID_BUTTON_SCAN 1003
#define IDC_RESULT_TEXT 1004
#define ID_BUTTON_ADD_VIRUS 1005
#define ID_BUTTON_EDIT_DISABLE 1006
#define ID_BUTTON_EDIT_STOP 1007

#define IDC_PASSWORD 1008
#define IDD_PASSWORD_DIALOG 1009
#define IDC_OLD_PASSWORD 1010
#define IDC_NEW_PASSWORD 1011
#define IDC_CONFIRM_PASSWORD 1012
#define ID_BUTTON_CHANGE_PASSWORD 1013
#define IDD_CHANGE_PASSWORD_DIALOG 1014
#define ID_BUTTON_EDIT_CUSTOM 1015

#define IDD_MONITORING_DIALOG 2001
#define IDC_COMBO_INTERVAL 2002
#define IDC_EDIT_CUSTOM_INTERVAL 2003
#define ID_BUTTON_MONITORING 2004

#endif
// Следующие стандартные значения для новых объектов
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
